# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(blank=True, max_length=250)),
                ('enddate', models.CharField(blank=True, max_length=250)),
                ('lock', models.CharField(blank=True, max_length=250)),
                ('projectcode', models.CharField(blank=True, max_length=250)),
                ('episode', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Table_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(blank=True, max_length=250)),
                ('enddate', models.CharField(blank=True, max_length=250)),
                ('project', models.CharField(blank=True, max_length=250)),
                ('process', models.CharField(blank=True, max_length=250)),
                ('product_type', models.CharField(blank=True, max_length=250)),
                ('episode', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
