# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180615_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='episode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lock',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='projectcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
