# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180616_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_schedule',
            name='episode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='table_schedule',
            name='process',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='table_schedule',
            name='product_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='table_schedule',
            name='project',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
