# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20180616_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='enddate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startdate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_schedule',
            name='enddate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_schedule',
            name='startdate',
            field=models.DateTimeField(blank=True),
        ),
    ]
