# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20180616_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_schedule',
            name='lock',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
