# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_table_schedule_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_schedule',
            name='schedule_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
