# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-05 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_table_schedule_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_schedule',
            name='schedule_id',
            field=models.IntegerField(default=datetime.datetime(2018, 8, 5, 12, 50, 4, 34895, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
