# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='user_role',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
