# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0004_genticketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genticketing',
            name='deadline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='genticketing',
            name='ids',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
