# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0005_auto_20171112_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='genticketing',
            name='Department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='genticketing',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
