# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0007_auto_20171118_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_files', models.FileField(upload_to=b'documents/')),
            ],
        ),
    ]
