# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0008_upload_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotno', models.CharField(blank=True, max_length=250)),
                ('episode', models.CharField(blank=True, max_length=250)),
                ('projectname', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
