# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0009_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='shots',
            name='assigned',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='shots',
            name='process',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='shots',
            name='supervisor',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
