# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0010_auto_20171209_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=250, null=True)),
                ('episodes', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shots',
            name='status',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
