# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0011_auto_20180107_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(blank=True, max_length=250)),
                ('branch', models.CharField(blank=True, max_length=250)),
                ('year', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
