# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0012_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subject',
            new_name='subjectdetails',
        ),
    ]
