# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0013_auto_20180115_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
