# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0015_genticketing_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='assests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.CharField(blank=True, max_length=200)),
                ('props', models.CharField(blank=True, max_length=200)),
                ('sets', models.CharField(blank=True, max_length=200)),
                ('vehicles', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
