# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0016_assests'),
    ]

    operations = [
        migrations.CreateModel(
            name='creteassestdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesttypes', models.CharField(blank=True, max_length=200)),
                ('nameofassests', models.CharField(blank=True, max_length=200)),
                ('assestprocess', models.CharField(blank=True, max_length=200)),
                ('processrelated', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
