# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0019_creteassestdata_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='renderdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(blank=True, max_length=200)),
                ('fromframe', models.TextField(blank=True, max_length=250, null=True)),
                ('toframe', models.TextField(blank=True, max_length=250, null=True)),
                ('totalframe', models.TextField(blank=True, max_length=250, null=True)),
                ('prioirty', models.CharField(blank=True, max_length=200)),
                ('renderdepth', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
