# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewaylogin', '0020_renderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderdata',
            name='task_ids',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
